name: Terraform

on:
  pull_request:
    branches: ["main", "develop"]
  push:
    branches: ["main", "develop"]
jobs:
  terraform-init:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v3
      - name: Terraform Init
        id: init
        run: terraform init

  terraform-validate:
    runs-on: ubuntu-latest
    needs: terraform-init
    steps:
      - name: Terraform Validate
        id: validate
        run: terraform validate

  terraform-fmt:
    runs-on: ubuntu-latest
    needs: terraform-validate
    steps:
      - name: Terraform fmt
        id: fmt
        run: terraform fmt -check

  terraform-plan:
    runs-on: ubuntu-latest
    needs: terraform-fmt
    steps:
      - name: Terraform Plan
        id: Plan
        run: terraform plan

#   terraform-apply:
#     runs-on: ubuntu-latest
#     needs: terraform-plan
#     steps:
#       - name: Terraform Apply
#         id: apply
#         run: terraform apply -auto-approve -input=false
