name: Terraform

on:
  pull_request:
    branches: ["main", "develop"]

jobs:
  Plan:
    environment: "dev"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.7.5
          terraform_wrapper: false

      - name: GCP Auth
        id: auth
        uses: "google-github-actions/auth@v1"
        with:
          credentials_json: "${{ secrets.GOOGLE_CREDENTIALS }}"

      - name: Terraform Init
        id: init
        run: terraform init

      - name: Terraform Validate
        id: validate
        run: terraform validate

      - name: Terraform fmt
        id: format
        run: terraform fmt -check

      - name: Terraform Plan
        id: plan
        run: |
          terraform plan  -out=tfplan
          terraform show tfplan

      - name: Save Artifact
        id: save-artifact
        uses: actions/upload-artifact@v3
        with:
          name: tf-plan
          path: ./tfplan

  Apply:
    environment: "prod"
    runs-on: ubuntu-latest
    needs: ["Plan"]
    steps:
      - uses: actions/checkout@v4

      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.7.5
          terraform_wrapper: false

      - name: GCP Auth
        id: auth
        uses: "google-github-actions/auth@v1"
        with:
          credentials_json: "${{ secrets.GOOGLE_CREDENTIALS }}"

      - name: Terraform Init
        id: init
        run: terraform init

      - name: Apply Terraform Changes
        run: terraform apply -auto-approve
