name: Terraform

on:
  pull_request:
    branches: ["main", "develop"]
  push:
    branches: ["main", "develop"]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v3

      - name: GCP Auth
        id: auth
        uses: "google-github-actions/auth@v1"
        with:
          credentials_json: "${{ secrets.GOOGLE_CREDENTIALS }}"

      - name: "Set up Cloud SDK"
        uses: "google-github-actions/setup-gcloud@v0.6.0"

      - name: Terraform Init
        id: init
        run: terraform init

      - name: Terraform Validate
        id: validate
        run: terraform validate

      - name: Terraform fmt
        id: fmt
        run: terraform fmt -check

      - name: Terraform Plan
        id: Plan
        run: |
          terraform plan -no-color -out=tfplan

      - name: Save Artifact
        id: save-artifact
        uses: actions/upload-artifact@v3
        with:
          name: tf-plan
          path: ./tfplan

      - name: Comment Plan
        id: comment-plan
        uses: peter-evans/create-or-update-comment@v2
        with:
          body: |
            Terraform Plan:
            ```
            ${{ steps.plan.outputs.plan }}
            ```
            Plan saved to GH artifacts.

#     - name: Terraform Apply
#       id: apply
#       run: terraform apply -auto-approve -input=false
